# FlowLM Experimental Configuration
# Only includes values that differ from structured config defaults

masking:
  strategy: "FLOWLM"

logging:
  wandb:
    name: "flowlm-experiment"
  save_dir: "checkpoints/flowlm"
  hf:
    model_name: "modernbert-large-flowlm"
