# LLaDA Baseline Configuration
# Only includes values that differ from structured config defaults

masking:
  strategy: "LLADA"

logging:
  wandb:
    name: "llada-baseline"
  save_dir: "checkpoints/llada"
  hf:
    model_name: "modernbert-large-dllm"
